#!/usr/bin/env bash
# This script reads /etc/passwd and displays user information in a 
formatted way.

while IFS=: read -r username password uid gid comment home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and 
rides $shell. USER ID's place is protected by the passcode $password, more 
info about the user here: $comment"
done < /etc/passwd
