#!/usr/bin/env bash
# This script finds and displays the PID and process name of processes whose name contains "bash"
cat /proc/*/cmdline 2>/dev/null | grep -a --null-data 'bash' | awk -F'/' '{print $3, $NF}'

